env :  Pendulum-v1
lr_actor        : 0.0005
lr_critic      : 0.001
featExtractor: !!python/name:__main__.NothingToDo ''
gamma        : 0.99
batch_size   : 32
alow: -10
ahigh: 10
eps_std: 0.02
buffer_limit : 50000
tau          : 0.005 # for target network soft update
freqTest: 100
action : 'OU' # if 'OU' then distribution is changed. 
freqSave: 1000
nbTest: 1
seed : 42
nbEpisodes : 1000000
freqVerbose: 100
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 300