env: gridworld-v0
map: gridworldPlans&Goals/plan2.txt
rewards:
  0: -0.001
  3: 1
  4: 1
  5: -1
  6: -1
seed: 5
featExtractor: !!python/name:__main__.MapFromDumpExtractor4 ''
copy_freq: 1000
train_freq: 10
learning_rate: 0.001
gamma: 0.99
epsilon: 0.2
buffer_size: 100000
batch_size: 1000
max_episodes: 1000000
max_timesteps: 100
